services:
  log-consumer-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8091:8091"
    environment:
      SERVER_PORT: 8091
      SPRING_PROFILES_ACTIVE: dev
      ELASTICSEARCH_ENDPOINT: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: mLekyz-kTSMd97oZbIEt
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
      - elasticsearch
    networks:
      - main-network

networks:
  main-network:
    external: true
